# https://docs.travis-ci.com/user/reference/overview/
dist: bionic
sudo: required
language: python
python:
-   "3.6"
install:
-   sudo add-apt-repository -y ppa:fkrull/deadsnakes
-   sudo apt-get -yq update
-   sudo apt-get -yq install python3.5 python3.5-dev python3.6 python3.6-dev python3.7 python3.7-dev
-   pip install tox "pylint<2.0"
script:
-   ./pep8.sh
-   tox
