dist: bionic
sudo: required
language: python
python:
-   "3.5"
install:
-   sudo add-apt-repository -y ppa:fkrull/deadsnakes
-   sudo apt-get -yq update
-   sudo apt-get -yq install python3.6 python3.6-dev python3.7 python3.7-dev
-   pip install tox "pylint<2.0"
script:
-   ./pep8.sh
-   tox
